[package]
name = "mytestrust"
version = "0.1.0"
authors = ["dop3ch3f <ifeanyi.ibekie@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
failure = "=0.1.5"
failure_derive = "=0.1.5"
backtrace = "=0.3.18"