[package]
name = "mytestrust"
version = "0.1.0"
authors = ["dop3ch3f <ifeanyi.ibekie@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "=0.12.0"
backtrace = "=0.3.18"